### ISSUE TITLE
bimodal.pickle not found

### ISSUE THREAD

**Issue by flydragon2018** [SenticNet/hfusion#1]
Using TensorFlow backend.
Traceback (most recent call last):
  File "hfusion.py", line 477, in <module>
    Trimodal()
  File "hfusion.py", line 355, in Trimodal
    maxlen = load_bimodal_activations()
  File "hfusion.py", line 111, in load_bimodal_activations
    with open('./bimodal.pickle', 'rb') as handle:
FileNotFoundError: [Errno 2] No such file or directory: './bimodal.pickle'

**Comment by flydragon2018** [comment]
my bad. I just ran it without reading the source code first.
It is commented out.

**Comment by LXM0708** [comment]
> Using TensorFlow backend.
> Traceback (most recent call last):
> File "hfusion.py", line 477, in
> Trimodal()
> File "hfusion.py", line 355, in Trimodal
> maxlen = load_bimodal_activations()
> File "hfusion.py", line 111, in load_bimodal_activations
> with open('./bimodal.pickle', 'rb') as handle:
> FileNotFoundError: [Errno 2] No such file or directory: './bimodal.pickle'

您好！请问这个文件在哪里，怎么运行呢
